# Generated by Django 4.0.4 on 2022-06-06 11:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='Null'),
        ),
    ]
