# Generated by Django 4.0.4 on 2022-06-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_video'),
        ('blog', '0010_alter_post_url'),
    ]

    operations = [
    ]
