# Generated by Django 4.0.4 on 2022-06-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_0009_video_0010_alter_post_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
